---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: host1
    image: skandikon.se/almalinux9-ansible-molecule
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - 127.0.0.1:80:80
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible